config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  root to: "producers#index"
  
  resources :artists
  resources :contracts
  resources :beats, only: [:show]
  resources :producers, only: [:index, :show]
  resources :sessions

  get "/", to: "producers#index"
  post "/sessions/reset", to: "sessions#reset"
  post "/sessions/new", to: "sessions#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: 'logout' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :contracts
    has_many :beats, through: :contracts 
    
    validates :name, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    
    has_secure_password

end

app/models/beat.rb
class Beat < ApplicationRecord
    belongs_to :producer
    has_many :contracts
    has_many :artists, through: :contracts 
    
end

app/models/contract.rb
class Contract < ApplicationRecord
    belongs_to :artist
    belongs_to :beat 

end

app/models/producer.rb
class Producer < ApplicationRecord
    has_many :beats
    has_many :contracts, through: :beats 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    #before_action :set_current_artist
    #before_action :authorized
    helper_method :current_user

    def current_user
      if session[:user_id]
        @current_user ||= Artist.find(session[:user_id])
      else
        @current_user = nil
      end
    end
  
    private
  
    def authorized
      if @current_artist == nil
        redirect_to login_path
      end
    end
  
    def set_current_artist
      @current_restaurant = Artist.find_by(id: session[:artist_id])
    end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def index
        @artists = Artist.all 
    end 

    def new 
        @artist = Artist.new
    end 

    def create
        @artist = Artist.create(artist_params)
        if @artist.valid?
            session[:artist_id] = @artist.id
            redirect_to @artist    
          else
            flash[:errors] = @artist.errors.full_messages
            redirect_to new_artist_path
          end
    end 

    def show
        @artist = Artist.find(params[:id])
    end 

    def edit
        @artist = Artist.find(params[:id])
    end 

    def update
        @artist = Artist.find(params[:id])
        @artist.update(artist_params)
        redirect_to @artist 
    end 

    def destroy
        @artist = Artist.find(params[:id])
        @artist.destroy
        #redirect to login page
    end 

    private

    def artist_params
        params.require(:artist).permit(:name, :email, :password)
    end


end

app/controllers/beats_controller.rb
class BeatsController < ApplicationController

    def show
        @beat = Beat.find(params[:id])
    end 

    


end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

    def new
        @contract = Contract.new
    end 

    def create
        # byebug
        @contract = Contract.create(contract_params)
        redirect_to contract_path(@contract) 
    end 

    
    def show
        @contract = Contract.find(params[:id])
    end 
    
    def edit
        @contract = Contract.find(params[:id])
    end
    
    def update
        @contract = Contract.create(params.require(:contract).permit(:price))
        redirect_to contract_path(@contract)
    end 

    def destroy
        @contract = Contract.find(params[:id])
        @contract.destroy
        redirect_to @contract.artist
    end 

    private 

    def contract_params
        params.require(:contract).permit(:artist_id, :beat_id, :price)
    end     


end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController

    def index
        @producers = Producer.all 
    end 

    def show
        @producer = Producer.find(params[:id])
    end 


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  # def create
  #   @artist = Artist.find_by(name: params[:name])
  #   if @artist && @artist.authenticate(params[:password])
  #     redirect_to @artist
  #   else
  #     redirect_to login_path
  #   end
  # end

  def create
    artist = Artist.find_by_name(params[:name])
    if artist && artist.authenticate(params[:password])
      session[:user_id] = artist.id
      redirect_to "/", notice: "Logged in!"
    else
      flash.now[:alert] = "Name or password is invalid" 
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to "/", notice: "Logged out!"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/beats_helper.rb
module BeatsHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/artists/edit.html.erb
<%= form_for @artist do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit "change artist name"  %>
<% end %>

app/views/artists/index.html.erb
<h1 class="index"> ARTISTS USING BEATBAY </h1>
<ul class="list-group">
<% @artists.each do |artist| %>
    <li class="list-group-item"> <%= artist.name %> </li>
<% end %>
</ul

app/views/artists/new.html.erb
<h1> Join BeatBay </h1>

<%= form_for @artist do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>

  <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error| %>
        <li class="error"><%= error %></li>
      <% end %>
    </ul>
  <% end %>

<%= f.submit "create account" %>
<% end %>

app/views/artists/show.html.erb
<h1 class="index"><%= @artist.name %></h1>
<ol>
<h2> Beats You Own </h2>
<% @artist.contracts.each do |contract| %>
   <ul class="list-group">
    Beat : <li class="list-group-item"><%= contract.beat.name %></li>
   
    Producer: <li class="list-group-item"><%= contract.beat.producer.name %></li>
    
    Contract: <li class="list-group-item"><%= link_to contract.beat.name, contract %> </li>
    
<% end %>
</ul>

<h4> <%= link_to "change info", edit_artist_path %>

app/views/beats/show.html.erb
<h1><%= @beat.name %></h1>
<ol>
<h3>By <%= @beat.producer.name %></h2>
<br>
<h4>Price: $ <%= @beat.price %></h4>
</ol>
<br>

<%= link_to "buy beat", new_contract_path %>

<div class="embed-responsive embed-responsive-1by1">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/2QwbV5LscBs"></iframe>
</div>

app/views/contracts/edit.html.erb
<h1> Contract </h1>
<h3> Contract Details including price </h3>


<%= form_for @contract do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>
<%= f.label :last_name %>
<%= f.text_field :last_name %>
<%= f.submit "I Agree"  %>
<% end %>



  

app/views/contracts/new.html.erb
<div class="card text-center" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Beat Lease Contract</h5>
    <p class="card-text"> 
Description:
The beat chosen is to be leased for non-exclusive lease; (for a 2 year lease). This fee is solely for
use, and is separate from royalties. The amount allows you to license this beat to make a song of your choice and publicly
display/sell for commercial use at your own discretion, while others can also contract to do the same. Every 2 years, a
new agreement for lease of beat can be negotiated.

Royalties:
The producer is entitled to 50% of money from song writing and
50% of money from publishing of the finished song.

Vocals & Beat/Instrumental:
The artist is entitled to do what they please with the vocals from the song with no obligation to the producer
(remixes, acapellas, etc.)
The producer is entitled to use the beat/instrumental at their own discretion, including leasing it to other artists.
Producer can use the beat for movies, video games, TV, shows, songs, etc.
Non-Exclusive Lease:
his is a non-exclusive lease (to the person signing the contract) that lasts 2 years and can be renegotiated after
every term. Multiple artists can lease this beat alongside your contract.
Requirements:
The producer credit must always be displayed in all written information regarding the song(s). It's each party's
responsibility to notify one another of any contact information changes within 6 months.  </p>
  </div>
</div>


<%= form_for @contract do |f| %>

<%= f.hidden_field :artist_id, value: current_user.id %>


<%= f.label :beat_id %>
<%= f.collection_select :beat_id, Beat.all, :id, :name %>

<%= f.submit "I Agree on the terms"  %>
<% end %>

app/views/contracts/show.html.erb
<h1> The Contract </h1>
<h1><%= @contract.beat.name %></h1>

<ol>
<h2>Artist Name: <%= @contract.artist.name %></h2>
<br>
<ol>
<h2> Price: $<%= @contract.beat.price %> </h2>
</ol>
</ol>

<h3> Cancel Lease Below </h3>
<%= button_to "Delete Contract", { :action => "destroy", :id => @contract.id },
          :confirm => "Are you sure?", :method => :delete %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">BeatBay</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Producers <span class="sr-only">(current)</span></a>
      </li>
      
      <% if current_user %>
        <li class="nav-item active">
            <a class="nav-link" href="<%= artist_path(Artist.find(session[:user_id])) %>">My Beats</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/logout">Log Out</a>
        </li>
      <% else %>
        <li class="nav-item active">
            <a class="nav-link" href="/login">Log In</a>
        </li>
      <% end %> 
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beatbay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render "layouts/nav" %>

  <body>
    <%= yield %>

    <div class="container">
      Copyright &copy; BeatBay 
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/producers/index.html.erb
<div class="index-video-wrapper">
  <%= video_tag "blaatina.mp4", autoplay: :autoplay, loop: :loop, mute: :mute, class: "index_video" %>


<ul>

</ul>
</div>

<h1 class="index"> Producers </h1>
<ul class="list-group">
<% @producers.each do |producer| %>
    <li class="list-group-item"> <%= link_to producer.name, producer %> </li>
<% end %>
</ul

app/views/producers/show.html.erb
<h1 class="index"><%= @producer.name %></h1>
<%= image_tag @producer.img_url %>
<br>
<h2> BEATS </h2>
<% @producer.beats.each do |beat| %>
<ul class="list-group">
<li class="list-group-item"><%= link_to beat.name, beat %></li>
<% end %>
</ul>